import os
import shutil
from snakemake.utils import min_version
from snakemake.utils import validate


# Settings --------------------------------------------------------------------

min_version("6.3.0")

shell.executable("bash")


configfile: os.path.join(workflow.basedir, "..", ".tests", "integration", "config", "config.yaml")


# Validating samples in rules/common


workdir: config["workdir"]


# Input rules ------------------------------------------------------------------


include: "rules/common.smk"


rule all:
    input:
        "staging/validation_status.json",
        "staging/isolates_datasheet.json",


# Includes --------------------------------------------------------------------


include: "rules/validate_input.smk"
include: "rules/validate_assemblies.smk"
include: "rules/staging.smk"


# Workflow --------------------------------------------------------------------
## send notifications with onsuccess and onerror


onstart:
    print(f"\nYou are using GEUEBT-VALIDATE version: {version}")
    with open(pipe_log, "a") as f:
        f.write(f"[{get_local_time()}]: Pipeline started\n")


onsuccess:
    try:
        for logfile in os.listdir(".snakemake/log/"):
            shutil.move(os.path.join(".snakemake/log", logfile), "logs")
        shutil.rmtree(".snakemake", ignore_errors=True)
    except:
        # if not executing .snakemake from workdir,
        # the log file will be in execution directory
        # as far as I know, there is now way to access this form here
        pass
    print("\nWorkflow finished, no error")
    with open(pipe_log, "a") as f:
        f.write(f"[{get_local_time()}]: Pipeline succesfully finished\n")
    # cleanup workdir
    if config["ephemeral"]:
        print("Cleaning up workdir, more space for you!")
        [shutil.rmtree(dir) for dir in next(os.walk('.'))[1] if not dir in ['validation', 'isolate_sheets', 'staging', 'logs']]


onerror:
    print(
        f"\nAn error occured, please consider filing an bug report."
        f"\n"
        f"\nIssue tracker: https://github.com/NRW-GEUBT/geuebt-validate/issues"
    )
    with open(pipe_log, "a") as f:
        f.write(f"[{get_local_time()}]: Pipeline stopped on error\n")
