# Configuration file template
# Modify the values below as deemed nescessary
# See the documentation for more informations
# ------------------------------------------------------------------------------

# Workflow control
# ----------------

# Path to the output directory, will be created if it doesn´t exist
workdir: /path/to/workdir
# Path to the metadata table
metadata: /path/to/metadata
# Path to the directory containing fasta files
fasta_dir: /path/to/dir

# Additional parameters
# ---------------------