name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f .tests/unit/requirements.txt ]; then pip install -r .tests/unit/requirements.txt; fi
    
    - name: Unit testing
      run: |
        pytest .tests/unit
    
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs --configfile .tests/config/config.yaml"
        stagein: |
            conda config --set channel_priority strict

